import os

import numpy as np

# Config
CONFIG_FILE_PATH = os.path.dirname(os.path.abspath(__file__)) + "/"

# Communication
SOCKET_DOCKER_ADDRESS = "tcp://0.0.0.0:"
PING_PORT = "5555"

SOCKET_ANY_ADDRESS = "tcp://*:"
GAME_CYCLE_PORT = "5556"
STREAM_PI_FEED_PORT = "5557"

# Pathfinding
# TODO Test at lab to find right radii value
ROBOT_RADIUS = 40
OBSTACLE_RADIUS = 12

# Vision
CALIBRATION_FILE_PATH = CONFIG_FILE_PATH + "numpy-1280x800.npz"
PUCK_TEMPLATE_LOCATION = CONFIG_FILE_PATH + "../infra/vision/templates/"


LAPTOP_CAMERA_INDEX = 0
PC_CAMERA_INDEX = 1

PIXEL_TO_METERS_RATIO = 514.4
PIXEL_TO_CENTIMETERS_RATIO = 5.144

OBSTACLE_ARUCO_MARKER_ID = 0
# in meter
OBSTACLE_ARUCO_MARKER_SIZE = 0.08
ROBOT_ARUCO_MARKER_ID = 1
ROBOT_ARUCO_MARKER_SIZE = 0.12
CALIBRATION_ARRAYS = np.load(CALIBRATION_FILE_PATH)
CAMERA_MATRIX = CALIBRATION_ARRAYS["camera_matrix"]
DISTORTION_COEFFICIENTS = CALIBRATION_ARRAYS["distortion_coefficients"]

WORLD_CAMERA_IMAGE_SIZE = (1280, 800)

# in meter
OBSTACLE_HEIGHT = 0.40
ROBOT_HEIGHT = 0.232

BASE_TABLE_IMAGE = (
    CONFIG_FILE_PATH + "../../resources/test/puck/puck_configuration_1.jpg"
)

DEFAULT_OHMMETER_POSITION = 165, 611

GRIPPER_OFFSET = 120
DEFAULT_PUCK_ZONE_POSITION = (1007, 408)

STARTING_ZONE_CORNERS_POSITION = [
    (506, 231),
    (502, 579),
    (156, 574),
    (158, 228),
]
STARTING_ZONE_CENTER_POSITION = (326, 405)
