SOCKET_DOCKER_ADDRESS = "tcp://0.0.0.0:"
PING_PORT = "5555"

SOCKET_ANY_ADDRESS = "tcp://*:"
GAME_CYCLE_PORT = "5556"

CALIBRATION_FILE_PATH = "src/config/numpy.npz"

LAPTOP_CAMERA_INDEX = 1
PC_CAMERA_INDEX = 0
