# Station communication
import os

SOCKET_DOCKER_BASE_ADDRESS = "tcp://covirondelle-station:"
SOCKET_LOCAL_BASE_ADDRESS = "tcp://localhost:"
PING_PORT = "5555"
# TODO Replace with IP address of station when at the lab
SOCKET_STATION_ADDRESS = "tcp://10.240.113.37:"

GAME_CYCLE_PORT = "5556"
STREAM_PI_FEED_PORT = "5557"

# Local
AN_IMAGE_PATH = (
    os.path.dirname(os.path.abspath(__file__))
    + "/../../resources/test/test_embedded_camera.jpg"
)

# Vision
TESSERACT_LOCATION = "/usr/bin/tesseract"
PIXEL_TO_CENTIMETERS = 6
# TODO Change for real values after testing in lab and with real images
PUCK_ALIGNMENT_X_CENTER_POSITION = 295
PUCK_ALIGNMENT_Y_CENTER_POSITION = 360
PUCK_ALIGNMENT_HORIZONTAL_THRESHOLD = 10
PUCK_ALIGNMENT_UP_THRESHOLD = 4
ALIGNED_OHMMETER_HORIZONTAL_POSITION = 330
OHMMETER_ALIGNMENT_THRESHOLD = 2
IMAGE_CENTER_POSITION = (320, 240)
STARTING_ZONE_CORNER_POSITION = (300, 275)

# STM-32
# TODO change port_name when on rpi
STM_PORT_NAME = "/dev/ttySTM32"
STM_BAUD_RATE = 115200

# Robot movement
# TODO test at lab to find optimal values
ROBOT_RADIUS = 0.1075
ROBOT_ROTATION_SPEED = 0.15
ROBOT_MAXIMUM_SPEED = 0.15
ROBOT_ALIGNMENT_SPEED = 0.02
SERVOING_CONSTANT = 5
BASE_COMMAND_DURATION = 0.1

# Maestro polulu
# TODO Change maestro port name
MAESTRO_POLULU_PORT_NAME = "/dev/ttyACM1"
GRIPPER_HORIZONTAL_SERVO_ID = 0
GRIPPER_VERTICAL_SERVO_ID = 1
CAMERA_HORIZONTAL_SERVO_ID = 2
CAMERA_VERTICAL_SERVO_ID = 3
SERVO_SPEED = 60
SERVO_ACCELERATION = 10

# Camera
CAMERA_INDEX = 0
EMBEDDED_CAMERA_IMAGE_SIZE = (640, 480)

# Camera servos
MAX_HORIZONTAL_ANGLE_VALUE = 8000
MIN_HORIZONTAL_ANGLE_VALUE = 3950
HORIZONTAL_ANGLE_RANGE = (MIN_HORIZONTAL_ANGLE_VALUE, MAX_HORIZONTAL_ANGLE_VALUE)
MIN_VERTICAL_ANGLE_VALUE = 3950
MAX_VERTICAL_ANGLE_VALUE = 800
VERTICAL_ANGLE_RANGE = (MIN_VERTICAL_ANGLE_VALUE, MAX_VERTICAL_ANGLE_VALUE)
CAMERA_LOOK_UP_TARGET = 6200
CAMERA_LOOK_DOWN_TARGET = 4062
HORIZONTAL_MIDDLE_TARGET = 6200

# Gripper servos
OPEN_GRIPPER_TARGET = 7000
CLOSE_GRIPPER_TARGET = 6000
MOVE_GRIPPER_UP_TARGET = 5000
MOVE_GRIPPER_DOWN_TARGET = 6500

# Gripper
CURRENT_CONSUMPTION_THRESHOLD = 200

# Resistance
RESISTANCE_READ_THRESHOLD = 1e6

# Command panel
NUMBER_OF_LETTERS_TO_READ = 9
COMMAND_PANEL_HORIZONTAL_POSITION = 160
COMMAND_PANEL_VERTICAL_POSITION = 21421

# wheel
POWER_SENT_TO_WHEELS = 12

# battery

TOTAL_CHARGE = 21600000
TIME_BETWEEN_COMMAND = 1
